"""
PDF report generation utilities for Big Five PDF report generation.
"""

from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from datetime import date


def generate_pdf_report(
    title, image_buffer, output_pdf_path, author=None, subtitle=None
):
    """
    Assemble a PDF report using ReportLab, embedding the bar graph image and applying layout/styling.
    """
    c = canvas.Canvas(output_pdf_path, pagesize=letter)
    width, height = letter
    margin = 0.75 * inch
    y = height - margin

    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(margin, y, title)
    y -= 0.4 * inch
    if subtitle:
        c.setFont("Helvetica", 14)
        c.drawString(margin, y, subtitle)
        y -= 0.3 * inch
    if author:
        c.setFont("Helvetica", 10)
        c.drawString(margin, y, f"Author: {author}")
        y -= 0.2 * inch
    c.setFont("Helvetica", 10)
    c.drawString(margin, y, f"Date: {date.today().isoformat()}")
    y -= 0.3 * inch

    # Bar graph image
    image_buffer.seek(0)
    img = ImageReader(image_buffer)
    img_width = 5.5 * inch
    img_height = 3.5 * inch
    c.drawImage(img, margin, y - img_height, width=img_width, height=img_height)
    y -= img_height + 0.3 * inch

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(
        width / 2, 0.5 * inch, "Generated by Big Five Questionnaire Report"
    )
    c.showPage()
    c.save()
