"""
PDF report generation utilities for Big Five PDF report generation.
"""

from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from datetime import date


def generate_pdf_report(
    title, image_buffer, output_pdf_path, author=None, subtitle=None
):
    """
    Assemble a PDF report using ReportLab, embedding the bar graph image and applying layout/styling.
    """
    c = canvas.Canvas(output_pdf_path, pagesize=landscape(letter))
    width, height = landscape(letter)
    margin = 0.75 * inch
    y = height - margin

    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(margin, y, title)
    y -= 0.4 * inch
    if subtitle:
        c.setFont("Helvetica", 14)
        c.drawString(margin, y, subtitle)
        y -= 0.3 * inch
    if author:
        c.setFont("Helvetica", 10)
        c.drawString(margin, y, f"Author: {author}")
        y -= 0.2 * inch
    c.setFont("Helvetica", 10)
    c.drawString(margin, y, f"Date: {date.today().isoformat()}")
    y -= 0.3 * inch

    # Bar graph image
    image_buffer.seek(0)
    img = ImageReader(image_buffer)
    # Use more of the landscape width
    img_width = width - 2 * margin
    # Make the image 40% taller
    img_height = (height / 2.2) * 1.4
    # Center the image vertically
    img_y = (height - img_height) / 2
    c.drawImage(img, margin, img_y, width=img_width, height=img_height)
    y = img_y - 0.3 * inch

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(
        width / 2, 0.5 * inch, "Generated by Big Five Questionnaire Report"
    )
    c.save()
