# Big Five Questionnaire Items
# Each item has: text, trait, and optional reverse (default: false)
#
# The 'reverse: true' flag means the item is reverse-scored (higher agreement indicates lower trait level).
# Responses should be on a 1-5 Likert scale (1 = Strongly Disagree, 5 = Strongly Agree).
items:
  # Openness
  - text: I enjoy trying new and different things.
    trait: Openness
  - text: I have a vivid imagination.
    trait: Openness
  - text: I enjoy reflecting on philosophical or abstract ideas.
    trait: Openness
  - text: I often enjoy playing with ideas just for fun.
    trait: Openness
  - text: I am curious about many different things.
    trait: Openness
  - text: I find comfort in doing things the same way every time.
    trait: Openness
    reverse: true
  - text: I enjoy thinking about concepts that challenge conventional wisdom.
    trait: Openness
  - text: I often come up with creative solutions to problems.
    trait: Openness
  # Conscientiousness
  - text: I pay attention to details.
    trait: Conscientiousness
  - text: I make plans and stick to them.
    trait: Conscientiousness
  - text: I am always prepared.
    trait: Conscientiousness
  - text: I do things efficiently and thoroughly.
    trait: Conscientiousness
  - text: I set goals and work steadily to achieve them.
    trait: Conscientiousness
  - text: I stay focused on my work even when there are distractions.
    trait: Conscientiousness
  - text: I often forget to put things back in their proper place.
    trait: Conscientiousness
    reverse: true
  - text: I struggle to stay on task when distracted.
    trait: Conscientiousness
    reverse: true
  # Extraversion
  - text: I feel comfortable around people.
    trait: Extraversion
  - text: I make friends easily.
    trait: Extraversion
  - text: I enjoy being the center of attention.
    trait: Extraversion
  - text: I feel energized after spending time with others.
    trait: Extraversion
  - text: I often prefer to be alone.
    trait: Extraversion
    reverse: true
  - text: I tend to keep in the background.
    trait: Extraversion
    reverse: true
  - text: I speak up in group settings, even with unfamiliar people.
    trait: Extraversion
  - text: I enjoy seeking out new and exciting experiences.
    trait: Extraversion
  # Agreeableness
  - text: I sympathize with others' feelings.
    trait: Agreeableness
  - text: I am interested in people's problems.
    trait: Agreeableness
  - text: I try to be courteous to everyone I meet.
    trait: Agreeableness
  - text: I make people feel at ease.
    trait: Agreeableness
  - text: I sometimes speak harshly when upset.
    trait: Agreeableness
    reverse: true
  - text: I am not interested in other people's problems.
    trait: Agreeableness
    reverse: true
  - text: I try to see things from other people's perspective.
    trait: Agreeableness
  - text: I avoid arguments, even when I feel strongly about something.
    trait: Agreeableness
  # Neuroticism
  - text: I get stressed out easily.
    trait: Neuroticism
  - text: I often feel anxious or worried.
    trait: Neuroticism
  - text: I frequently feel blue or down.
    trait: Neuroticism
  - text: I have frequent mood swings.
    trait: Neuroticism
  - text: I remain calm under pressure.
    trait: Neuroticism
    reverse: true
  - text: I usually bounce back quickly from emotional setbacks.
    trait: Neuroticism
    reverse: true
  - text: When things go wrong, I struggle to stop worrying.
    trait: Neuroticism
  - text: I find it hard to calm myself when upset.
    trait: Neuroticism

  # ──────────────────────────
  # New items added (10 total)
  # ──────────────────────────

  - text: I am deeply moved by works of art, music, or poetry.
    trait: Openness
  - text: I rarely seek out unfamiliar cultures or cuisines.
    trait: Openness
    reverse: true

  - text: I double-check important tasks to make sure they are done correctly.
    trait: Conscientiousness
  - text: I often act on impulse without considering the consequences.
    trait: Conscientiousness
    reverse: true

  - text: I usually strike up conversations with strangers.
    trait: Extraversion
  - text: I rarely show my enthusiasm openly.
    trait: Extraversion
    reverse: true

  - text: I believe most people are basically honest and trustworthy.
    trait: Agreeableness
  - text: I insist on getting my own way, even when others disagree.
    trait: Agreeableness
    reverse: true

  - text: I often feel embarrassed or self-conscious in social situations.
    trait: Neuroticism
  - text: Minor setbacks can leave me feeling angry or irritated for hours.
    trait: Neuroticism
